[default]

[default.vegetables]
    "абельмош" = "Abelmos"
    "авокадо" = "Avocado"
    "ангурия" = "Anguria"
    "арракача" = "Arrakacha"
    "аррорут" = "Arrowroot"
    "артишок" = "Artichoke"
    "базелла" = "Basella"
    "базилик" = "Basil"
    "баклажан" = "Eggplant"
    "бамия" = "Okra"
    "батат" = "Sweet potato"
    "белокопытник" = "Butterbur"
    "бобы" = "Beans"
    "бок-чой" = "Bok choy"
    "брокколи" = "Broccoli"
    "брюква" = "Swede"
    "буряк" = "Buriak"
    "габлиция" = "Gablicia"
    "горох" = "Peas"
    "горчица" = "Mustard"
    "дайкон" = "Daikon"
    "жеруха" = "Watercress"
    "зелень" = "Greens"
    "ипомея" = "Morning glory"
    "кабачок" = "Zucchini"
    "каперсы" = "Capers"
    "капуста" = "Cabbage"
    "капуста белокочанная" = "White cabbage"
    "капуста брюссельская" = "Brussels sprouts"
    "капуста краснокочанная" = "Red Cabbage"
    "капуста пекинская" = "Chinese Cabbage"
    "капуста романеско" = "Romanesco cabbage"
    "капуста савойская" = "Savoy cabbage"
    "картофель" = "Potatoes"
    "катран" = "Katran"
    "кивано" = "Kiwano"
    "кислица" = "Kislitsa"
    "козлобородник" = "Salsify"
    "колоцинт" = "Colocynth"
    "кольраби" = "Kohlrabi"
    "корнишон" = "Gherkin"
    "кукуруза" = "Corn"
    "лагенария" = "Lagenaria"
    "латук" = "Lettuce"
    "лук" = "Onion"
    "лук-порей" = "Leek"
    "лук-шалот" = "Shallot"
    "люффа" = "Luffa"
    "майоран" = "Marjoram"
    "мака" = "Poppy"
    "мелотрия" = "Melotria"
    "момордика" = "Momordica"
    "морковь" = "Carrot"
    "настурция" = "Nasturtium"
    "нут" = "Chickpea"
    "огурец" = "Cucumber"
    "пак-чой" = "Pak Choi"
    "пастернак" = "Parsnip"
    "патиссон" = "Squash"
    "перец" = "Pepper"
    "перец сладкий" = "Bell pepper"
    "перец болгарский" = "Bell pepper"
    "петрушка" = "Parsley"
    "плантан" = "Plantane"
    "помидор" = "Tomato"
    "радиккьо" = "Radicchio"
    "ревень" = "Rhubarb"
    "редис" = "Radish"
    "редька" = "Radish"
    "редька чёрная" = "Black radish"
    "репа" = "Turnip"
    "руккола" = "Arugula"
    "салат" = "Salad"
    "сараха" = "Saraha"
    "свекла" = "Beet"
    "сельдерей" = "Celery"
    "спаржа" = "Asparagus"
    "томат" = "Tomato"
    "топинамбур" = "Jerusalem artichoke"
    "трихозант" = "Trihozant"
    "турнепс" = "Turnips"
    "тыква" = "Pumpkin"
    "укроп" = "Dill"
    "уллюко" = "Ulyuko"
    "фасоль" = "Beans"
    "фенхель" = "Fennel"
    "хикама" = "Hikama"
    "хрен" = "Horseradish"
    "циклантера" = "Cyclanter"
    "цуккини" = "Zucchini"
    "чабер" = "Savory"
    "чайот" = "Chayote"
    "черри" = "Cherry tomatoes"
    "чеснок" = "Garlic"
    "чили" = "Chile"
    "чистец" = "Purist"
    "чуфа" = "Chufa"
    "шнитт-лук" = "Chives"
    "шпинат" = "Spinach"
    "щавель" = "Sorrel"
    "эстрагон" = "Tarragon"
    "якон" = "Yacon"
    "ямс" = "Yam"

[default.fruits]
    "абрикос" = "Apricot"
    "авокадо" = "Avocado"
    "айва" = "Quince"
    "алыча" = "Cherry plum"
    "ананас" = "Pineapple"
    "апельсин" = "Orange"
    "арбуз" = "Watermelon"
    "банан" = "Banana"
    "боярышник" = "Hawthorn"
    "виноград" = "Grapes"
    "вишня" = "Cherry"
    "гранат" = "Garnet"
    "грейпфрут" = "Grapefruit"
    "груша" = "Pear"
    "гуава" = "Guava"
    "джекфрут" = "Jackfruit"
    "дуриан" = "Durian"
    "дыня" = "Melon"
    "звёздчатое яблоко" = "Star apple"
    "инжир" = "Figs"
    "ирга" = "Irga"
    "какао" = "Cocoa"
    "карамбола" = "Carambola"
    "кешью" = "Cashew nuts"
    "киви" = "Kiwi"
    "кизил" = "Dogwood"
    "кокос" = "Coconut"
    "королёк" = "Kinglet"
    "кумкват" = "Kumquat"
    "лайм" = "Lime"
    "лимон" = "Lemon"
    "личи" = "Lychee"
    "малина" = "Raspberry"
    "манго" = "Mango"
    "мандарин" = "Mandarin"
    "маракуйя" = "Passion fruit"
    "нектарин" = "Nectarine"
    "папайя" = "Papaya"
    "персик" = "Peach"
    "питайя" = "Pitaya"
    "питахайя" = "Pitahaya"
    "помело" = "Pomelo"
    "саусеп" = "Sausep"
    "свити" = "Sweety"
    "слива" = "Plum"
    "тамарилло" = "Tamarillo"
    "тамаринд" = "Tamarind"
    "фейхоа" = "Feijoa"
    "фига" = "Figs"
    "физалис" = "Physalis"
    "хурма" = "Persimmon"
    "черёмуха" = "Bird cherry"
    "черешня" = "Cherries"
    "шелковица" = "Mulberry"
    "яблоко" = "Apple"